FROM python:3.9.8

# 创建文件夹
RUN mkdir /nsfw

# 拷贝文件
COPY *.sh /nsfw/
COPY *.py /nsfw/
COPY requirements.txt /nsfw/requirements.txt
COPY whl /nsfw/whl
COPY Model /nsfw/Model

# 指定工作空间
WORKDIR /nsfw

# 安装依赖
RUN pip install --no-index --find-links=whl -r requirements.txt && \
	chmod +x run.sh

ENTRYPOINT ["/nsfw/run.sh"]